services:
  ollama:
    # 使用するimageを指定
    image: ollama/ollama:latest
    container_name: ollama
    # このコンテナのPC上でのport, docker内部のportをそれぞれ11434に設定
    ports:
      - "11434:11434"
    # コンテナを再度起動した際に前回ダウンロードしたモデルを使用できるようにvolumeを使用
    volumes:
      - ollama_data:/root/.ollama
    # GPUを使用する場合 (NVIDIAの場合)　GPUを持たない場合コメントアウトしてください
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always

  app:
	  # 使用するimageにDockerfileで作成されるimageを指定
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    # localのfileのコピー先である/appを作業ディレクトリに指定
    working_dir: /app
    # ollamaコンテナにアクセスするためのurlを設定
    # pythonのollamaライブラリの使用時などに設定が必要
    environment:
      - OLLAMA_HOST=http://ollama:11434
    # /appディレクトリの変更をlocalのコピー元に反映
    # uv syncでのcacheを保存し次回起動時に利用
    volumes:
      - .:/app:delegated            # ローカルソース
      - uv_cache:/root/.cache/uv    # uv キャッシュ
    # 初回起動でpyproject.pyが存在しない(uv initが実行されていない時)uv initを実行、その後動作確認をし、containerを起動し続ける。
    command: ["sh", "-c", "[ -x pyproject.py ] || uv init; uv run hello.py; tail -f /dev/null"]

	# ollamaコンテナが停止した場合appコンテナも停止
    depends_on:
      - ollama
    restart: no

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on: [otel-collector]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ["--config=/otel-collector-config.yaml"]   # パスを明示
    volumes:
      - ./otel-collector-config.yaml:/otel-collector-config.yaml  # ${PWD} を避ける

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data
    environment:
      - CHROMA_OPEN_TELEMETRY__ENDPOINT=http://otel-collector:4317/
      - CHROMA_OPEN_TELEMETRY__SERVICE_NAME=chroma
    depends_on:
      - otel-collector
      - zipkin

volumes:
  ollama_data:
  chroma_data:
  uv_cache: